## **Problem Statement**

Organizations are increasingly recognizing the pivotal role customer feedback plays in shaping the trajectory of their products and services. The ability to swiftly and effectively respond to customer input not only fosters enhanced customer experiences but also serves as a catalyst for growth, prolonged customer engagement, and the nurturing of lifetime value relationships.

While organizations may be inundated with a wealth of customer-generated feedback and support tickets, the product management role entails much more than just processing the inputs.

To make efforts in managing customer experience and expectations truly impactful, it is necessary to adopt a structured approach – a method that allows to discern the most pressing issues, set priorities, and allocate resources judiciously. One of the most effective strategies is the power of Support Ticket Categorization.

### Objective

This exercise develops an advanced support ticket categorization system that accurately classifies incoming tickets, assigns relevant tags based on their content, implements mechanisms and generate the first response based on the sentiment for prioritizing tickets for prompt resolution.

## **Installing and Importing Libraries and Dependencies**

In [ ]:
# Installation for GPU llama-cpp-python

!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.2.45 --force-reinstall --no-cache-dir -q

In [1]:
# Installation for CPU llama-cpp-python

!CMAKE_ARGS="-DLLAMA_CUBLAS=off" FORCE_CMAKE=1 pip install llama-cpp-python==0.2.45 --force-reinstall --no-cache-dir -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.7/36.7 MB 147.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 197.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 310.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 235.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 195.5 MB/s eta 0:00:00
  Building wheel for llama-cpp-python (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.5.3 which is incompatible.

**Note** : There may be an error related to a dependency issue thrown by the pip package. This can be ignored as it will not impact the execution of the code.

In [2]:
# For downloading the models from Hugging Face Hub
!pip install huggingface_hub==0.20.3 pandas==1.5.3 -q

  Installing build dependencies ... done
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [3]:
# Function to download the model from the Hugging Face model hub
from huggingface_hub import hf_hub_download

# Importing the Llama class from the llama_cpp module
from llama_cpp import Llama

# Importing the json module
import json

# for loading and manipulating data
import pandas as pd

# for time computations
import time

import warnings
warnings.filterwarnings("ignore")

## **Loading the Data**

In [4]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rebeccaoshea/support-ticket-text-data-mid-term-nlp-project")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'support-ticket-text-data-mid-term-nlp-project' dataset.
Path to dataset files: /kaggle/input/support-ticket-text-data-mid-term-nlp-project

In [5]:
# Install if needed
!pip install -q kagglehub

import pandas as pd
from pathlib import Path

# Download the dataset
dataset_directory = Path(
    kagglehub.dataset_download(
        "rebeccaoshea/support-ticket-text-data-mid-term-nlp-project"
    )
)

print("Dataset directory:", dataset_directory)

# Find every CSV in the downloaded directory
csv_files = list(dataset_directory.rglob("*.csv"))

print("\nCSV files found:")
for file in csv_files:
    print(file)

Using Colab cache for faster access to the 'support-ticket-text-data-mid-term-nlp-project' dataset.
Dataset directory: /kaggle/input/support-ticket-text-data-mid-term-nlp-project

CSV files found:
/kaggle/input/support-ticket-text-data-mid-term-nlp-project/Support_ticket_text_data_mid_term.csv

In [6]:
csv_path = dataset_directory / "Support_ticket_text_data_mid_term.csv"

# Fallback in case the file is inside a subdirectory
if not csv_path.exists():
    matches = [
        file for file in csv_files
        if file.name.lower() == "Support_ticket_text_data_mid_term.csv"
    ]

    if not matches:
        raise FileNotFoundError(
            f"Support_ticket_text_data_mid_term.csv was not found. Available files: {csv_files}"
        )

    csv_path = matches[0]

print("Loading:", csv_path)

ticket_data = pd.read_csv(csv_path)

display(ticket_data.head())

Loading: /kaggle/input/support-ticket-text-data-mid-term-nlp-project/Support_ticket_text_data_mid_term.csv

  support_tick_id                                support_ticket_text
0      ST2023-006  My internet connection has significantly slowe...
1      ST2023-007  Urgent help required! My laptop refuses to sta...
2      ST2023-008  I've accidentally deleted essential work docum...
3      ST2023-009  Despite being in close proximity to my Wi-Fi r...
4      ST2023-010  My smartphone battery is draining rapidly, eve...

## **Data Overview**

In [10]:
# The first 5 rows of the data
ticket_data.head(5)

  support_tick_id                                support_ticket_text
0      ST2023-006  My internet connection has significantly slowe...
1      ST2023-007  Urgent help required! My laptop refuses to sta...
2      ST2023-008  I've accidentally deleted essential work docum...
3      ST2023-009  Despite being in close proximity to my Wi-Fi r...
4      ST2023-010  My smartphone battery is draining rapidly, eve...

In [11]:
# The shape of the data
ticket_data.shape

(21, 2)

In [12]:
# Check for missing values in the data
ticket_data.isnull().sum()

support_tick_id        0
support_ticket_text    0
dtype: int64

## **Model Building**

### Loading the model

In [13]:
model_name_or_path = "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
model_basename = "mistral-7b-instruct-v0.2.Q6_K.gguf"

In [14]:
model_path = hf_hub_download(
    repo_id=model_name_or_path,
    filename=model_basename

)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

mistral-7b-instruct-v0.2.Q6_K.gguf: reconstructing file:   0%|          |  0.00B / 5.94GB

mistral-7b-instruct-v0.2.Q6_K.gguf: downloading bytes:           |  0.00B

In [15]:
llm = Llama(
     model_path=model_path,
     n_ctx=1024,
 )

llama_model_loader: loaded meta data with 24 key-value pairs and 291 tensors from /root/.cache/huggingface/hub/models--TheBloke--Mistral-7B-Instruct-v0.2-GGUF/snapshots/3a6fbf4a41a1d52e415a4958cde6856d34b2db93/mistral-7b-instruct-v0.2.Q6_K.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai_mistral-7b-instruct-v0.2
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 18
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  20:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  21:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  22:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q6_K:  226 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q6_K
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 5.53 GiB (6.56 BPW)
llm_load_print_meta: general.name     = mistralai_mistral-7b-instruct-v0.2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.11 MiB
llm_load_tensors:        CPU buffer size =  5666.09 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 1024
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =   128.00 MiB
llama_new_context_with_model: KV self size  =  128.00 MiB, K (f16):   64.00 MiB, V (f16):   64.00 MiB
llama_new_context_with_model:        CPU input buffer size   =    11.01 MiB
llama_new_context_with_model:        CPU compute buffer size =    96.00 MiB
llama_new_context_with_model: graph splits (measure): 1
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 |
Model metadata: {'tokenizer.chat_template': "{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}", 'tokenizer.ggml.add_eos_token': 'false', 'tokenizer.ggml.padding_token_id': '0', 'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'general.architecture': 'llama', 'llama.rope.freq_base': '1000000.000000', 'llama.context_length': '32768', 'general.name': 'mistralai_mistral-7b-instruct-v0.2', 'tokenizer.ggml.add_bos_token': 'true', 'llama.embedding_length': '4096', 'llama.feed_forward_length': '14336', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'llama.rope.dimension_count': '128', 'tokenizer.ggml.bos_token_id': '1', 'llama.attention.head_count': '32', 'llama.block_count': '32', 'llama.attention.head_count_kv': '8', 'general.quantization_version': '2', 'tokenizer.ggml.model': 'llama', 'general.file_type': '18'}
Using chat template: {{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}
Using chat eos_token:
Using chat bos_token:

In [16]:
#this is in case CPU is working instead of GPU

llm = Llama(
     model_path=model_path,
    n_ctx=1024, # Context window
    n_cores=-2 # Number of CPU cores to use
)

llama_model_loader: loaded meta data with 24 key-value pairs and 291 tensors from /root/.cache/huggingface/hub/models--TheBloke--Mistral-7B-Instruct-v0.2-GGUF/snapshots/3a6fbf4a41a1d52e415a4958cde6856d34b2db93/mistral-7b-instruct-v0.2.Q6_K.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai_mistral-7b-instruct-v0.2
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 18
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  20:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  21:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  22:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q6_K:  226 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q6_K
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 5.53 GiB (6.56 BPW)
llm_load_print_meta: general.name     = mistralai_mistral-7b-instruct-v0.2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.11 MiB
llm_load_tensors:        CPU buffer size =  5666.09 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 1024
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:        CPU KV buffer size =   128.00 MiB
llama_new_context_with_model: KV self size  =  128.00 MiB, K (f16):   64.00 MiB, V (f16):   64.00 MiB
llama_new_context_with_model:        CPU input buffer size   =    11.01 MiB
llama_new_context_with_model:        CPU compute buffer size =    96.00 MiB
llama_new_context_with_model: graph splits (measure): 1
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 |
Model metadata: {'tokenizer.chat_template': "{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}", 'tokenizer.ggml.add_eos_token': 'false', 'tokenizer.ggml.padding_token_id': '0', 'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'general.architecture': 'llama', 'llama.rope.freq_base': '1000000.000000', 'llama.context_length': '32768', 'general.name': 'mistralai_mistral-7b-instruct-v0.2', 'tokenizer.ggml.add_bos_token': 'true', 'llama.embedding_length': '4096', 'llama.feed_forward_length': '14336', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'llama.rope.dimension_count': '128', 'tokenizer.ggml.bos_token_id': '1', 'llama.attention.head_count': '32', 'llama.block_count': '32', 'llama.attention.head_count_kv': '8', 'general.quantization_version': '2', 'tokenizer.ggml.model': 'llama', 'general.file_type': '18'}
Using chat template: {{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}
Using chat eos_token:
Using chat bos_token:

## **Ticket Categorization and Returning Structured Output**

In [17]:
# creating a copy of the data
data_1 = ticket_data.copy()

In [18]:
#Defining the response funciton for Task 1.
def response_1(prompt,ticket):
    model_output = llm(
      f"""
      Q: {prompt}
      Support ticket: {ticket}
      A:
      """,
      max_tokens=512, #Number of tokens the model should generate for this task.
      stop=["Q:", "\n"],
      temperature=0.001, #The value for temperature.
      echo=False,
    )

    temp_output = model_output["choices"][0]["text"]
    final_output = temp_output[temp_output.index('{'):]

    return final_output

In [19]:
prompt_1 = """
    You are an AI analyzing ticket text. Classify the tickets using one or more of the below mentioned categories only
    and not any other depending upon the content of the ticket complaint:
    - Hardware problem
    - Software problem
    - Connectivity failures
    - Data recovery

    Format the output as a JSON object with a single key-value pair as shown below:
    {"category": "your_category_prediction"}
"""

In [20]:
start = time.time()
data_1['model_response'] = data_1['support_ticket_text'].apply(lambda x: response_1(prompt_1, x))
end = time.time()

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       6.04 ms /     9 runs   (    0.67 ms per token,  1490.56 tokens per second)
llama_print_timings: prompt eval time =  102410.52 ms /   162 tokens (  632.16 ms per token,     1.58 tokens per second)
llama_print_timings:        eval time =    7680.27 ms /     8 runs   (  960.03 ms per token,     1.04 tokens per second)
llama_print_timings:       total time =  110152.90 ms /   170 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       6.75 ms /     9 runs   (    0.75 ms per token,  1334.12 tokens per second)
llama_print_timings: prompt eval time =   29938.43 ms /    51 tokens (  587.03 ms per token,     1.70 tokens per second)
llama_print_timings:        eval time =    8346.98 ms /     8 runs   ( 1043.37 ms per token,     0.96 tokens per second)
llama_print_timings:       total time =   38344.18 ms /    59 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       4.83 ms /     8 runs   (    0.60 ms per token,  1656.31 tokens per second)
llama_print_timings: prompt eval time =   28575.67 ms /    47 tokens (  607.99 ms per token,     1.64 tokens per second)
llama_print_timings:        eval time =    5810.14 ms /     7 runs   (  830.02 ms per token,     1.20 tokens per second)
llama_print_timings:       total time =   34429.75 ms /    54 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      10.51 ms /     9 runs   (    1.17 ms per token,   856.25 tokens per second)
llama_print_timings: prompt eval time =   38747.51 ms /    58 tokens (  668.06 ms per token,     1.50 tokens per second)
llama_print_timings:        eval time =    9029.19 ms /     8 runs   ( 1128.65 ms per token,     0.89 tokens per second)
llama_print_timings:       total time =   47849.21 ms /    66 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       6.34 ms /     9 runs   (    0.70 ms per token,  1418.44 tokens per second)
llama_print_timings: prompt eval time =   18483.03 ms /    32 tokens (  577.59 ms per token,     1.73 tokens per second)
llama_print_timings:        eval time =    7207.99 ms /     8 runs   (  901.00 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =   25758.73 ms /    40 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       6.17 ms /     9 runs   (    0.69 ms per token,  1457.73 tokens per second)
llama_print_timings: prompt eval time =   17576.36 ms /    30 tokens (  585.88 ms per token,     1.71 tokens per second)
llama_print_timings:        eval time =    7444.10 ms /     8 runs   (  930.51 ms per token,     1.07 tokens per second)
llama_print_timings:       total time =   25080.30 ms /    38 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       6.14 ms /     9 runs   (    0.68 ms per token,  1466.51 tokens per second)
llama_print_timings: prompt eval time =   19216.19 ms /    33 tokens (  582.31 ms per token,     1.72 tokens per second)
llama_print_timings:        eval time =    7315.96 ms /     8 runs   (  914.50 ms per token,     1.09 tokens per second)
llama_print_timings:       total time =   26594.03 ms /    41 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       6.83 ms /     9 runs   (    0.76 ms per token,  1316.94 tokens per second)
llama_print_timings: prompt eval time =   20366.05 ms /    35 tokens (  581.89 ms per token,     1.72 tokens per second)
llama_print_timings:        eval time =    7151.40 ms /     8 runs   (  893.93 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =   27577.72 ms /    43 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       7.36 ms /     8 runs   (    0.92 ms per token,  1086.96 tokens per second)
llama_print_timings: prompt eval time =   17855.73 ms /    30 tokens (  595.19 ms per token,     1.68 tokens per second)
llama_print_timings:        eval time =    7125.72 ms /     7 runs   ( 1017.96 ms per token,     0.98 tokens per second)
llama_print_timings:       total time =   25039.17 ms /    37 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       5.54 ms /     9 runs   (    0.61 ms per token,  1626.02 tokens per second)
llama_print_timings: prompt eval time =   22700.81 ms /    37 tokens (  613.54 ms per token,     1.63 tokens per second)
llama_print_timings:        eval time =    6533.82 ms /     8 runs   (  816.73 ms per token,     1.22 tokens per second)
llama_print_timings:       total time =   29283.39 ms /    45 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       4.83 ms /     8 runs   (    0.60 ms per token,  1657.69 tokens per second)
llama_print_timings: prompt eval time =   19494.61 ms /    32 tokens (  609.21 ms per token,     1.64 tokens per second)
llama_print_timings:        eval time =    5755.00 ms /     7 runs   (  822.14 ms per token,     1.22 tokens per second)
llama_print_timings:       total time =   25291.38 ms /    39 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       5.67 ms /     9 runs   (    0.63 ms per token,  1588.14 tokens per second)
llama_print_timings: prompt eval time =   21774.35 ms /    36 tokens (  604.84 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =    6517.52 ms /     8 runs   (  814.69 ms per token,     1.23 tokens per second)
llama_print_timings:       total time =   28343.34 ms /    44 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       5.24 ms /     8 runs   (    0.65 ms per token,  1528.18 tokens per second)
llama_print_timings: prompt eval time =   21157.42 ms /    35 tokens (  604.50 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =    5892.42 ms /     7 runs   (  841.77 ms per token,     1.19 tokens per second)
llama_print_timings:       total time =   27097.21 ms /    42 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       4.79 ms /     8 runs   (    0.60 ms per token,  1669.80 tokens per second)
llama_print_timings: prompt eval time =   16549.71 ms /    26 tokens (  636.53 ms per token,     1.57 tokens per second)
llama_print_timings:        eval time =    5578.44 ms /     7 runs   (  796.92 ms per token,     1.25 tokens per second)
llama_print_timings:       total time =   22171.13 ms /    33 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       5.46 ms /     9 runs   (    0.61 ms per token,  1648.65 tokens per second)
llama_print_timings: prompt eval time =   20179.07 ms /    33 tokens (  611.49 ms per token,     1.64 tokens per second)
llama_print_timings:        eval time =    7185.04 ms /     8 runs   (  898.13 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =   27413.17 ms /    41 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       6.03 ms /     9 runs   (    0.67 ms per token,  1493.78 tokens per second)
llama_print_timings: prompt eval time =   13081.16 ms /    22 tokens (  594.60 ms per token,     1.68 tokens per second)
llama_print_timings:        eval time =    7300.86 ms /     8 runs   (  912.61 ms per token,     1.10 tokens per second)
llama_print_timings:       total time =   20442.41 ms /    30 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       6.12 ms /     9 runs   (    0.68 ms per token,  1469.63 tokens per second)
llama_print_timings: prompt eval time =   16235.58 ms /    28 tokens (  579.84 ms per token,     1.72 tokens per second)
llama_print_timings:        eval time =    7042.12 ms /     8 runs   (  880.27 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   23336.79 ms /    36 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       4.90 ms /     8 runs   (    0.61 ms per token,  1633.99 tokens per second)
llama_print_timings: prompt eval time =   13768.18 ms /    23 tokens (  598.62 ms per token,     1.67 tokens per second)
llama_print_timings:        eval time =    5564.57 ms /     7 runs   (  794.94 ms per token,     1.26 tokens per second)
llama_print_timings:       total time =   19375.07 ms /    30 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       5.70 ms /     8 runs   (    0.71 ms per token,  1403.26 tokens per second)
llama_print_timings: prompt eval time =   14569.33 ms /    25 tokens (  582.77 ms per token,     1.72 tokens per second)
llama_print_timings:        eval time =    6411.11 ms /     7 runs   (  915.87 ms per token,     1.09 tokens per second)
llama_print_timings:       total time =   21035.68 ms /    32 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       5.42 ms /     9 runs   (    0.60 ms per token,  1660.52 tokens per second)
llama_print_timings: prompt eval time =  103816.70 ms /   175 tokens (  593.24 ms per token,     1.69 tokens per second)
llama_print_timings:        eval time =    6542.88 ms /     8 runs   (  817.86 ms per token,     1.22 tokens per second)
llama_print_timings:       total time =  110416.40 ms /   183 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       7.73 ms /    12 runs   (    0.64 ms per token,  1551.99 tokens per second)
llama_print_timings: prompt eval time =  182101.20 ms /   289 tokens (  630.11 ms per token,     1.59 tokens per second)
llama_print_timings:        eval time =   15385.21 ms /    11 runs   ( 1398.66 ms per token,     0.71 tokens per second)
llama_print_timings:       total time =  197569.81 ms /   300 tokens

In [21]:
print("Time taken ",(end-start))

Time taken  912.8417797088623

In [22]:
#Checking the first five rows of the data to confirm whether the new column was added
data_1['model_response'].head()

0    {"category": "Connectivity failures"}
1         {"category": "Hardware problem"}
2            {"category": "Data recovery"}
3    {"category": "Connectivity failures"}
4         {"category": "Hardware problem"}
Name: model_response, dtype: object

In [23]:
# A function to parse the JSON output from the model
def extract_json_data(json_str):
    try:
        # Find the indices of the opening and closing curly braces
        json_start = json_str.find('{')
        json_end = json_str.rfind('}')

        if json_start != -1 and json_end != -1:
            extracted_category = json_str[json_start:json_end + 1]  # Extract the JSON object
            data_dict = json.loads(extracted_category)
            return data_dict
        else:
            print(f"Warning: JSON object not found in response: {json_str}")
            return {}
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}")
        return {}

In [24]:
i = 12
print(data_1.loc[i, 'support_ticket_text'])

I accidentally spilled water on my laptop, and it won't turn on. Can you help me assess the damage and recover my data?

In [25]:
print(data_1.loc[i, 'model_response'])

{"category": "Data recovery"}

After running a few examples, the prompt works because it adds the right class.

In [26]:
data_1["model_response_parsed"] = data_1["model_response"].apply(extract_json_data)

In [27]:
data_1["model_response_parsed"]

0               {'category': 'Connectivity failures'}
1                    {'category': 'Hardware problem'}
2                       {'category': 'Data recovery'}
3               {'category': 'Connectivity failures'}
4                    {'category': 'Hardware problem'}
5               {'category': 'Connectivity failures'}
6                    {'category': 'Software problem'}
7                    {'category': 'Hardware problem'}
8                       {'category': 'Data recovery'}
9                    {'category': 'Hardware problem'}
10                      {'category': 'Data recovery'}
11                   {'category': 'Hardware problem'}
12                      {'category': 'Data recovery'}
13                      {'category': 'Data recovery'}
14                   {'category': 'Hardware problem'}
15              {'category': 'Connectivity failures'}
16              {'category': 'Connectivity failures'}
17                      {'category': 'Data recovery'}
18                      {'category': 'Data recovery'}
19              {'category': 'Connectivity failures'}
20    {'category': 'Software problem, Data recovery'}
Name: model_response_parsed, dtype: object

In [28]:
data_1['model_response_parsed'].value_counts()

model_response_parsed
{'category': 'Data recovery'}                      7
{'category': 'Connectivity failures'}              6
{'category': 'Hardware problem'}                   6
{'category': 'Software problem'}                   1
{'category': 'Software problem, Data recovery'}    1
Name: count, dtype: int64

In [29]:
data_1[data_1["model_response_parsed"]=={}]

Empty DataFrame
Columns: [support_tick_id, support_ticket_text, model_response, model_response_parsed]
Index: []

In [30]:
model_response_parsed_df_1 = pd.json_normalize(data_1["model_response_parsed"])
model_response_parsed_df_1.head()

                category
0  Connectivity failures
1       Hardware problem
2          Data recovery
3  Connectivity failures
4       Hardware problem

In [31]:
# Concatenate the two dataframes
data_with_parsed_model_output_1 = pd.concat([data_1, model_response_parsed_df_1], axis=1)
data_with_parsed_model_output_1.head()

,support_tick_id,support_ticket_text,model_response,model_response_parsed,category
0,ST2023-006,My internet connection has significantly slowe...,"{""category"": ""Connectivity failures""}",{'category': 'Connectivity failures'},Connectivity failures
1,ST2023-007,Urgent help required! My laptop refuses to sta...,"{""category"": ""Hardware problem""}",{'category': 'Hardware problem'},Hardware problem
2,ST2023-008,I've accidentally deleted essential work docum...,"{""category"": ""Data recovery""}",{'category': 'Data recovery'},Data recovery
3,ST2023-009,Despite being in close proximity to my Wi-Fi r...,"{""category"": ""Connectivity failures""}",{'category': 'Connectivity failures'},Connectivity failures
4,ST2023-010,"My smartphone battery is draining rapidly, eve...","{""category"": ""Hardware problem""}",{'category': 'Hardware problem'},Hardware problem

In [32]:
final_data_1 = data_with_parsed_model_output_1.drop(['model_response','model_response_parsed'], axis=1)
final_data_1.head()

,support_tick_id,support_ticket_text,category
0,ST2023-006,My internet connection has significantly slowe...,Connectivity failures
1,ST2023-007,Urgent help required! My laptop refuses to sta...,Hardware problem
2,ST2023-008,I've accidentally deleted essential work docum...,Data recovery
3,ST2023-009,Despite being in close proximity to my Wi-Fi r...,Connectivity failures
4,ST2023-010,"My smartphone battery is draining rapidly, eve...",Hardware problem

##  Creating Tags

In [33]:
# creating a copy of the data
data_2 = ticket_data.copy()

In [34]:
def response_2(prompt,ticket,category):
    model_output = llm(
      f"""
      Q: {prompt}
      Support ticket: {ticket}
      Category: {category}
      A:
      """,
      max_tokens=512, #Setting the maximum number of tokens the model should generate for this task.
      stop=["Q:", "\n"],
      temperature=0.001, #Setting the value for temperature.
      echo=False,
    )

    temp_output = model_output["choices"][0]["text"]
    final_output = temp_output[temp_output.index('{'):]

    return final_output

In [35]:
prompt_2 = """
   You are an AI analyzing ticket text. Classify the tickets using one or more of the below mentioned categories only and not any other depending upon the content of the ticket complaint:
    - Hardware problem
    - Software problem
    - Connectivity failures
    - Data recovery

    Subsequently, add to each ticket one or more of the below mentioned keywords depending upon the content of the ticket text:
    - laptop
    - smartphone
    - USB
    - document loss
    - password
    - internet signal
    - battery
    - access problem

    Format the overall output as a JSON object with a key-value pair as shown below:
    {"category": "your_category_prediction", "tag": "your_tag_prediction"}

    Ensure that every ticket has at least one category and one tag.
"""

In [36]:
start = time.time()
data_2["model_response_2"]=final_data_1[['support_ticket_text','category']].apply(lambda x: response_2(prompt_2, x[0],x[1]),axis =1)
end = time.time()

Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      11.03 ms /    17 runs   (    0.65 ms per token,  1541.39 tokens per second)
llama_print_timings: prompt eval time =  149191.77 ms /   249 tokens (  599.16 ms per token,     1.67 tokens per second)
llama_print_timings:        eval time =   15235.28 ms /    16 runs   (  952.20 ms per token,     1.05 tokens per second)
llama_print_timings:       total time =  164545.65 ms /   265 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      10.93 ms /    17 runs   (    0.64 ms per token,  1554.78 tokens per second)
llama_print_timings: prompt eval time =   34159.68 ms /    58 tokens (  588.96 ms per token,     1.70 tokens per second)
llama_print_timings:        eval time =   13927.04 ms /    16 runs   (  870.44 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   48192.68 ms /    74 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       9.51 ms /    15 runs   (    0.63 ms per token,  1576.79 tokens per second)
llama_print_timings: prompt eval time =   32065.03 ms /    53 tokens (  605.00 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =   12146.98 ms /    14 runs   (  867.64 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   44300.51 ms /    67 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      11.11 ms /    17 runs   (    0.65 ms per token,  1529.74 tokens per second)
llama_print_timings: prompt eval time =   38956.88 ms /    65 tokens (  599.34 ms per token,     1.67 tokens per second)
llama_print_timings:        eval time =   13958.37 ms /    16 runs   (  872.40 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   53025.03 ms /    81 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      10.36 ms /    16 runs   (    0.65 ms per token,  1545.00 tokens per second)
llama_print_timings: prompt eval time =   23640.08 ms /    39 tokens (  606.16 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =   13077.12 ms /    15 runs   (  871.81 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   36822.18 ms /    54 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      10.88 ms /    17 runs   (    0.64 ms per token,  1563.22 tokens per second)
llama_print_timings: prompt eval time =   21377.06 ms /    37 tokens (  577.76 ms per token,     1.73 tokens per second)
llama_print_timings:        eval time =   14375.80 ms /    16 runs   (  898.49 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =   35858.27 ms /    53 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      11.12 ms /    17 runs   (    0.65 ms per token,  1528.36 tokens per second)
llama_print_timings: prompt eval time =   23860.65 ms /    39 tokens (  611.81 ms per token,     1.63 tokens per second)
llama_print_timings:        eval time =   13928.66 ms /    16 runs   (  870.54 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   37892.03 ms /    55 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      10.68 ms /    17 runs   (    0.63 ms per token,  1591.61 tokens per second)
llama_print_timings: prompt eval time =   25254.06 ms /    42 tokens (  601.29 ms per token,     1.66 tokens per second)
llama_print_timings:        eval time =   14043.19 ms /    16 runs   (  877.70 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   39397.84 ms /    58 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      15.11 ms /    16 runs   (    0.94 ms per token,  1059.25 tokens per second)
llama_print_timings: prompt eval time =   22641.99 ms /    36 tokens (  628.94 ms per token,     1.59 tokens per second)
llama_print_timings:        eval time =   22229.29 ms /    15 runs   ( 1481.95 ms per token,     0.67 tokens per second)
llama_print_timings:       total time =   45021.83 ms /    51 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      13.04 ms /    20 runs   (    0.65 ms per token,  1533.62 tokens per second)
llama_print_timings: prompt eval time =   26463.41 ms /    44 tokens (  601.44 ms per token,     1.66 tokens per second)
llama_print_timings:        eval time =   16459.56 ms /    19 runs   (  866.29 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   43051.04 ms /    63 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      10.93 ms /    17 runs   (    0.64 ms per token,  1555.35 tokens per second)
llama_print_timings: prompt eval time =   23021.27 ms /    38 tokens (  605.82 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =   13882.59 ms /    16 runs   (  867.66 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   37007.14 ms /    54 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      10.80 ms /    17 runs   (    0.64 ms per token,  1573.93 tokens per second)
llama_print_timings: prompt eval time =   25627.13 ms /    43 tokens (  595.98 ms per token,     1.68 tokens per second)
llama_print_timings:        eval time =   13849.43 ms /    16 runs   (  865.59 ms per token,     1.16 tokens per second)
llama_print_timings:       total time =   39579.72 ms /    59 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      10.80 ms /    16 runs   (    0.68 ms per token,  1480.93 tokens per second)
llama_print_timings: prompt eval time =   24587.24 ms /    41 tokens (  599.69 ms per token,     1.67 tokens per second)
llama_print_timings:        eval time =   13028.61 ms /    15 runs   (  868.57 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   37711.61 ms /    56 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       9.25 ms /    14 runs   (    0.66 ms per token,  1512.86 tokens per second)
llama_print_timings: prompt eval time =   18479.59 ms /    32 tokens (  577.49 ms per token,     1.73 tokens per second)
llama_print_timings:        eval time =   11326.06 ms /    13 runs   (  871.24 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   29895.05 ms /    45 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      11.08 ms /    17 runs   (    0.65 ms per token,  1534.02 tokens per second)
llama_print_timings: prompt eval time =   23976.90 ms /    40 tokens (  599.42 ms per token,     1.67 tokens per second)
llama_print_timings:        eval time =   13676.48 ms /    16 runs   (  854.78 ms per token,     1.17 tokens per second)
llama_print_timings:       total time =   37760.14 ms /    56 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      10.98 ms /    17 runs   (    0.65 ms per token,  1547.99 tokens per second)
llama_print_timings: prompt eval time =   16904.72 ms /    29 tokens (  582.92 ms per token,     1.72 tokens per second)
llama_print_timings:        eval time =   13860.87 ms /    16 runs   (  866.30 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   30868.35 ms /    45 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      11.06 ms /    17 runs   (    0.65 ms per token,  1537.63 tokens per second)
llama_print_timings: prompt eval time =   21472.00 ms /    35 tokens (  613.49 ms per token,     1.63 tokens per second)
llama_print_timings:        eval time =   13875.38 ms /    16 runs   (  867.21 ms per token,     1.15 tokens per second)
llama_print_timings:       total time =   35450.80 ms /    51 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      11.78 ms /    17 runs   (    0.69 ms per token,  1442.76 tokens per second)
llama_print_timings: prompt eval time =   16880.69 ms /    29 tokens (  582.09 ms per token,     1.72 tokens per second)
llama_print_timings:        eval time =   13749.74 ms /    16 runs   (  859.36 ms per token,     1.16 tokens per second)
llama_print_timings:       total time =   30740.58 ms /    45 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      10.37 ms /    16 runs   (    0.65 ms per token,  1542.91 tokens per second)
llama_print_timings: prompt eval time =   18948.37 ms /    31 tokens (  611.24 ms per token,     1.64 tokens per second)
llama_print_timings:        eval time =   13106.64 ms /    15 runs   (  873.78 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   32156.41 ms /    46 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =       1.21 ms /     2 runs   (    0.61 ms per token,  1648.80 tokens per second)
llama_print_timings: prompt eval time =  109249.46 ms /   182 tokens (  600.27 ms per token,     1.67 tokens per second)
llama_print_timings:        eval time =     924.91 ms /     1 runs   (  924.91 ms per token,     1.08 tokens per second)
llama_print_timings:       total time =  110187.79 ms /   183 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      10.29 ms /    16 runs   (    0.64 ms per token,  1555.06 tokens per second)
llama_print_timings: prompt eval time =  186421.06 ms /   298 tokens (  625.57 ms per token,     1.60 tokens per second)
llama_print_timings:        eval time =   21403.42 ms /    15 runs   ( 1426.89 ms per token,     0.70 tokens per second)
llama_print_timings:       total time =  207931.11 ms /   313 tokens

In [37]:
print("Time taken ",end-start)

Time taken  1177.6256408691406

In [38]:
data_2['model_response_2'].head()

0    {"category": "Connectivity failures", "tag": "...
1    {"category": "Hardware problem", "tag": "laptop"}
2    {"category": "Data recovery", "tag": "document...
3    {"category": "Connectivity failures", "tag": "...
4    {"category": "Hardware problem", "tag": "batte...
Name: model_response_2, dtype: object

In [39]:
i = 13
print(data_2.loc[i, 'support_ticket_text'])

My USB flash drive is physically damaged, and I need assistance in recovering critical files from it.

In [40]:
print(data_2.loc[i, 'model_response_2'])

{"category": "Data recovery", "tag": "USB"}

In [41]:
# Applying the function to the model response
data_2['model_response_parsed_2'] = data_2['model_response_2'].apply(extract_json_data)

Warning: JSON object not found in response: {

In [42]:
data_2["model_response_parsed_2"]

0     {'category': 'Connectivity failures', 'tag': '...
1     {'category': 'Hardware problem', 'tag': 'laptop'}
2     {'category': 'Data recovery', 'tag': 'document...
3     {'category': 'Connectivity failures', 'tag': '...
4     {'category': 'Hardware problem', 'tag': 'batte...
5     {'category': 'Connectivity failures', 'tag': '...
6     {'category': 'Software problem', 'tag': 'perfo...
7     {'category': 'Hardware problem', 'tag': 'laptop'}
8     {'category': 'Data recovery', 'tag': 'external...
9     {'category': 'Hardware problem', 'tag': 'lapto...
10    {'category': 'Data recovery', 'tag': 'document...
11    {'category': 'Hardware problem', 'tag': 'laptop'}
12       {'category': 'Data recovery', 'tag': 'laptop'}
13          {'category': 'Data recovery', 'tag': 'USB'}
14    {'category': 'Hardware problem', 'tag': 'laptop'}
15    {'category': 'Connectivity failures', 'tag': '...
16    {'category': 'Connectivity failures', 'tag': '...
17    {'category': 'Data recovery', 'tag': 'document...
18    {'category': 'Data recovery', 'tag': 'hard_dri...
19                                                   {}
20    {'category': 'Software problem', 'tag': 'docum...
Name: model_response_parsed_2, dtype: object

In [43]:
# Normalizing the model_response_parsed column
model_response_parsed_df_2 = pd.json_normalize(data_2['model_response_parsed_2'])
model_response_parsed_df_2.head()

                category              tag
0  Connectivity failures  internet signal
1       Hardware problem           laptop
2          Data recovery    document loss
3  Connectivity failures  internet signal
4       Hardware problem          battery

In [44]:
# Concatinating two dataframes
data_with_parsed_model_output_2 = pd.concat([data_2, model_response_parsed_df_2], axis=1)
data_with_parsed_model_output_2.head()

,support_tick_id,support_ticket_text,model_response_2,model_response_parsed_2,category,tag
0,ST2023-006,My internet connection has significantly slowe...,"{""category"": ""Connectivity failures"", ""tag"": ""...","{'category': 'Connectivity failures', 'tag': '...",Connectivity failures,internet signal
1,ST2023-007,Urgent help required! My laptop refuses to sta...,"{""category"": ""Hardware problem"", ""tag"": ""laptop""}","{'category': 'Hardware problem', 'tag': 'laptop'}",Hardware problem,laptop
2,ST2023-008,I've accidentally deleted essential work docum...,"{""category"": ""Data recovery"", ""tag"": ""document...","{'category': 'Data recovery', 'tag': 'document...",Data recovery,document loss
3,ST2023-009,Despite being in close proximity to my Wi-Fi r...,"{""category"": ""Connectivity failures"", ""tag"": ""...","{'category': 'Connectivity failures', 'tag': '...",Connectivity failures,internet signal
4,ST2023-010,"My smartphone battery is draining rapidly, eve...","{""category"": ""Hardware problem"", ""tag"": ""batte...","{'category': 'Hardware problem', 'tag': 'batte...",Hardware problem,battery

In [45]:
# Dropping model_response and model_response_parsed columns
final_data_2 = data_with_parsed_model_output_2.drop(['model_response_2','model_response_parsed_2'], axis=1)
final_data_2.head()

,support_tick_id,support_ticket_text,category,tag
0,ST2023-006,My internet connection has significantly slowe...,Connectivity failures,internet signal
1,ST2023-007,Urgent help required! My laptop refuses to sta...,Hardware problem,laptop
2,ST2023-008,I've accidentally deleted essential work docum...,Data recovery,document loss
3,ST2023-009,Despite being in close proximity to my Wi-Fi r...,Connectivity failures,internet signal
4,ST2023-010,"My smartphone battery is draining rapidly, eve...",Hardware problem,battery

In [46]:
# Checking the value counts of Category column
final_data_2['tag'].value_counts()

tag
internet signal          5
laptop                   5
document loss            2
document loss, USB       2
performance issue        1
battery                  1
external hard drive      1
laptop, graphics card    1
USB                      1
hard_drive               1
Name: count, dtype: int64

In [47]:
final_data_2 = final_data_2[["support_tick_id","support_ticket_text","category","tag"]]
final_data_2

,support_tick_id,support_ticket_text,category,tag
0,ST2023-006,My internet connection has significantly slowe...,Connectivity failures,internet signal
1,ST2023-007,Urgent help required! My laptop refuses to sta...,Hardware problem,laptop
2,ST2023-008,I've accidentally deleted essential work docum...,Data recovery,document loss
3,ST2023-009,Despite being in close proximity to my Wi-Fi r...,Connectivity failures,internet signal
4,ST2023-010,"My smartphone battery is draining rapidly, eve...",Hardware problem,battery
5,ST2023-011,I'm locked out of my online banking account an...,Connectivity failures,internet signal
6,ST2023-012,"My computer's performance is sluggish, severel...",Software problem,performance issue
7,ST2023-013,I'm experiencing a recurring blue screen error...,Hardware problem,laptop
8,ST2023-014,My external hard drive isn't being recognized ...,Data recovery,external hard drive
9,ST2023-015,The graphics card in my gaming laptop seems to...,Hardware problem,"laptop, graphics card"
10,ST2023-016,I accidentally formatted my USB drive with cri...,Data recovery,"document loss, USB"
11,ST2023-017,"My computer's screen has gone black, and I can...",Hardware problem,laptop
12,ST2023-018,"I accidentally spilled water on my laptop, and...",Data recovery,laptop
13,ST2023-019,"My USB flash drive is physically damaged, and ...",Data recovery,USB
14,ST2023-020,"The touchpad on my laptop has stopped working,...",Hardware problem,laptop
15,ST2023-021,"My internet connection is frequently dropping,...",Connectivity failures,internet signal
16,ST2023-022,Wi-Fi is inconsistent despite proximity to the...,Connectivity failures,internet signal
17,ST2023-023,I accidentally formatted my USB drive with cru...,Data recovery,"document loss, USB"
18,ST2023-024,"My external hard drive isn't being recognized,...",Data recovery,hard_drive
19,ST2023-025,I am experiencing a critical problem with my i...,NaN,NaN
20,ST2023-026,I hope this message finds you well. I am writi...,Software problem,document loss

## **Assigning Priority and ETA**

In [48]:
# creating a copy of the data
data_3 = final_data_2.copy()

In [49]:
def response_3(prompt,ticket,category,tag):
    model_output = llm(
      f"""
      Q: {prompt}
      Support ticket: {ticket}
      category: {category}
      tag: {tag}
      A:
      """,
      max_tokens=512,
      stop=["Q:"],
      temperature=0.0,
      echo=False,
    )

    temp_output = model_output["choices"][0]["text"]
    final_output = temp_output[temp_output.index('{'):]

    return final_output

In [50]:
prompt_3 = """
You are an IT service-desk triage assistant.

Using the existing ticket category and tags, assign an operational priority
and response ETA. Do not classify category or tags again.

Priority definitions:

HIGH URGENCY:
Assign High urgency only when the ticket contains concrete evidence of at
least one of the following:

1. An active security or account-compromise risk.
2. Ongoing data loss or physical damage that may become worse if the
   device continues to be used.
3. Complete loss of access to a business-critical system or device,
   with no reasonable workaround.
4. A specific near-term business deadline that will be missed unless
   the issue is addressed quickly.
5. Multiple users or an essential business service are affected.

NORMAL:
Assign Normal when the issue is inconvenient but there is no evidence of
immediate business, security, or data-loss impact. Examples include:

- Slow or intermittent connectivity when some service remains available.
- Battery drain, performance degradation, weak Wi-Fi, or peripheral problems.
- Problems with a reasonable temporary workaround.
- Requests where the user provides no evidence of an imminent deadline,
  active damage, security risk, or complete inability to work.

Important rules:

- Emotional words such as "urgent", "critical", "important", or "please help"
  are not sufficient by themselves for High urgency.
- A Data recovery category is not automatically High urgency.
- If the evidence is insufficient or ambiguous, choose Normal.
- Do not force a particular number or percentage of tickets into either class.
- Base the decision on operational impact, not the customer's tone.

ETA mapping:
- High urgency -> 1 business day
- Normal -> 2 to 3 business days

Return exactly one JSON object:

{
  "priority": "High urgency or Normal",
  "eta": "1 business day or 2 to 3 business days",
  "priority_reason": "Brief evidence-based explanation"
}
"""

**Note**: The output of the model should be in a structured format (JSON format).

In [51]:
# Applying generate_llama_response function on support_ticket_text column
start = time.time()
data_3['model_response_new'] = final_data_2[['support_ticket_text','category','tag']].apply(lambda x: response_3(prompt_3, x[0],x[1],x[2]),axis=1)
end = time.time()

Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      58.32 ms /    89 runs   (    0.66 ms per token,  1525.98 tokens per second)
llama_print_timings: prompt eval time =  338784.18 ms /   556 tokens (  609.32 ms per token,     1.64 tokens per second)
llama_print_timings:        eval time =   79229.38 ms /    88 runs   (  900.33 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =  418647.71 ms /   644 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      44.52 ms /    60 runs   (    0.74 ms per token,  1347.83 tokens per second)
llama_print_timings: prompt eval time =   38226.92 ms /    63 tokens (  606.78 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =   63031.92 ms /    59 runs   ( 1068.34 ms per token,     0.94 tokens per second)
llama_print_timings:       total time =  101680.52 ms /   122 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      34.74 ms /    54 runs   (    0.64 ms per token,  1554.36 tokens per second)
llama_print_timings: prompt eval time =   36282.54 ms /    59 tokens (  614.96 ms per token,     1.63 tokens per second)
llama_print_timings:        eval time =   46943.37 ms /    53 runs   (  885.72 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =   83568.98 ms /   112 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      49.89 ms /    77 runs   (    0.65 ms per token,  1543.30 tokens per second)
llama_print_timings: prompt eval time =   42858.79 ms /    71 tokens (  603.64 ms per token,     1.66 tokens per second)
llama_print_timings:        eval time =   66746.55 ms /    76 runs   (  878.24 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =  110106.30 ms /   147 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      38.80 ms /    60 runs   (    0.65 ms per token,  1546.27 tokens per second)
llama_print_timings: prompt eval time =   26648.57 ms /    44 tokens (  605.65 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =   51907.40 ms /    59 runs   (  879.79 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   78949.42 ms /   103 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      40.30 ms /    62 runs   (    0.65 ms per token,  1538.58 tokens per second)
llama_print_timings: prompt eval time =   26007.09 ms /    43 tokens (  604.82 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =   53411.52 ms /    61 runs   (  875.60 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   79835.79 ms /   104 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      47.66 ms /    74 runs   (    0.64 ms per token,  1552.50 tokens per second)
llama_print_timings: prompt eval time =   27463.52 ms /    45 tokens (  610.30 ms per token,     1.64 tokens per second)
llama_print_timings:        eval time =   63932.45 ms /    73 runs   (  875.79 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   91870.23 ms /   118 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      57.32 ms /    88 runs   (    0.65 ms per token,  1535.29 tokens per second)
llama_print_timings: prompt eval time =   29263.68 ms /    47 tokens (  622.63 ms per token,     1.61 tokens per second)
llama_print_timings:        eval time =   76615.12 ms /    87 runs   (  880.63 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =  106457.04 ms /   134 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      50.64 ms /    78 runs   (    0.65 ms per token,  1540.38 tokens per second)
llama_print_timings: prompt eval time =   36152.36 ms /    43 tokens (  840.75 ms per token,     1.19 tokens per second)
llama_print_timings:        eval time =   68184.44 ms /    77 runs   (  885.51 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =  104839.24 ms /   120 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      44.65 ms /    69 runs   (    0.65 ms per token,  1545.46 tokens per second)
llama_print_timings: prompt eval time =   31422.75 ms /    52 tokens (  604.28 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =   61853.92 ms /    68 runs   (  909.62 ms per token,     1.10 tokens per second)
llama_print_timings:       total time =   93723.59 ms /   120 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      45.00 ms /    69 runs   (    0.65 ms per token,  1533.47 tokens per second)
llama_print_timings: prompt eval time =   27579.79 ms /    46 tokens (  599.56 ms per token,     1.67 tokens per second)
llama_print_timings:        eval time =   59466.39 ms /    68 runs   (  874.51 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   87502.05 ms /   114 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      50.84 ms /    76 runs   (    0.67 ms per token,  1494.83 tokens per second)
llama_print_timings: prompt eval time =   29854.01 ms /    48 tokens (  621.96 ms per token,     1.61 tokens per second)
llama_print_timings:        eval time =   66074.52 ms /    75 runs   (  880.99 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   96417.70 ms /   123 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      54.20 ms /    82 runs   (    0.66 ms per token,  1513.03 tokens per second)
llama_print_timings: prompt eval time =   27623.47 ms /    46 tokens (  600.51 ms per token,     1.67 tokens per second)
llama_print_timings:        eval time =   71340.66 ms /    81 runs   (  880.75 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   99494.65 ms /   127 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      39.42 ms /    61 runs   (    0.65 ms per token,  1547.48 tokens per second)
llama_print_timings: prompt eval time =   22528.97 ms /    37 tokens (  608.89 ms per token,     1.64 tokens per second)
llama_print_timings:        eval time =   53513.46 ms /    60 runs   (  891.89 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =   76429.49 ms /    97 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      53.65 ms /    77 runs   (    0.70 ms per token,  1435.15 tokens per second)
llama_print_timings: prompt eval time =   27387.67 ms /    45 tokens (  608.61 ms per token,     1.64 tokens per second)
llama_print_timings:        eval time =   79547.53 ms /    76 runs   ( 1046.68 ms per token,     0.96 tokens per second)
llama_print_timings:       total time =  107481.62 ms /   121 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      66.18 ms /    98 runs   (    0.68 ms per token,  1480.79 tokens per second)
llama_print_timings: prompt eval time =   21873.61 ms /    35 tokens (  624.96 ms per token,     1.60 tokens per second)
llama_print_timings:        eval time =   86319.65 ms /    97 runs   (  889.89 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =  108842.84 ms /   132 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      51.38 ms /    79 runs   (    0.65 ms per token,  1537.68 tokens per second)
llama_print_timings: prompt eval time =   24971.34 ms /    41 tokens (  609.06 ms per token,     1.64 tokens per second)
llama_print_timings:        eval time =   68688.02 ms /    78 runs   (  880.62 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   94174.60 ms /   119 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      51.28 ms /    78 runs   (    0.66 ms per token,  1521.03 tokens per second)
llama_print_timings: prompt eval time =   22807.81 ms /    37 tokens (  616.43 ms per token,     1.62 tokens per second)
llama_print_timings:        eval time =   67796.70 ms /    77 runs   (  880.48 ms per token,     1.14 tokens per second)
llama_print_timings:       total time =   91105.57 ms /   114 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      51.41 ms /    78 runs   (    0.66 ms per token,  1517.36 tokens per second)
llama_print_timings: prompt eval time =   23405.14 ms /    38 tokens (  615.92 ms per token,     1.62 tokens per second)
llama_print_timings:        eval time =   69374.16 ms /    77 runs   (  900.96 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =   93300.32 ms /   115 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      79.69 ms /   111 runs   (    0.72 ms per token,  1392.88 tokens per second)
llama_print_timings: prompt eval time =  115517.96 ms /   185 tokens (  624.42 ms per token,     1.60 tokens per second)
llama_print_timings:        eval time =  109577.30 ms /   110 runs   (  996.16 ms per token,     1.00 tokens per second)
llama_print_timings:       total time =  225909.26 ms /   295 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      62.43 ms /    92 runs   (    0.68 ms per token,  1473.60 tokens per second)
llama_print_timings: prompt eval time =  186768.62 ms /   301 tokens (  620.49 ms per token,     1.61 tokens per second)
llama_print_timings:        eval time =   82760.41 ms /    91 runs   (  909.46 ms per token,     1.10 tokens per second)
llama_print_timings:       total time =  270172.11 ms /   392 tokens

In [52]:
print("Time taken ",(end-start))

Time taken  2620.853367090225

In [53]:
i = 10
print(data_3.loc[i, 'support_ticket_text'])

I accidentally formatted my USB drive with critical work files. Can you guide me through the data recovery process to retrieve these files?

In [54]:
print(data_3.loc[i, 'model_response_new'])

{
        "priority": "Normal",
        "eta": "2 to 3 business days",
        "priority_reason": "The data loss occurred due to user error, which does not meet the criteria for High urgency. The data can be recovered using standard data recovery tools and processes."
      }

In [55]:
# Applying the function to the model response
data_3['model_response_parsed_new'] = data_3['model_response_new'].apply(extract_json_data)
data_3['model_response_parsed_new'].head()

0    {'priority': 'Normal', 'eta': '2 to 3 business...
1    {'priority': 'High urgency', 'eta': '1 busines...
2    {'priority': 'High urgency', 'eta': '1 busines...
3    {'priority': 'Normal', 'eta': '2 to 3 business...
4    {'priority': 'Normal', 'eta': '2 to 3 business...
Name: model_response_parsed_new, dtype: object

In [56]:
# Normalizing the model_response_parsed column
model_response_parsed_df_3 = pd.json_normalize(data_3['model_response_parsed_new'])
model_response_parsed_df_3.head(10)

,priority,eta,priority_reason
0,Normal,2 to 3 business days,The user reports a significant slowdown in int...
1,High urgency,1 business day,The user has provided concrete evidence of a s...
2,High urgency,1 business day,The user has reported substantial data loss wh...
3,Normal,2 to 3 business days,The issue is inconvenient but there is no evid...
4,Normal,2 to 3 business days,The user reports a battery issue but there is ...
5,High urgency,1 business day,The user's inability to access their online ba...
6,Normal,2 to 3 business days,The user's productivity is impacted by a perfo...
7,Normal,2 to 3 business days,The user is experiencing a recurring blue scre...
8,Normal,2 to 3 business days,The data recovery category alone does not indi...
9,Normal,2 to 3 business days,The issue is a hardware problem affecting a si...

In [82]:
# Concatinating the two dataframes
data_with_parsed_model_output_3 = pd.concat([data_3, model_response_parsed_df_3], axis=1)
data_with_parsed_model_output_3.head()

,support_tick_id,support_ticket_text,category,tag,model_response_new,model_response_parsed_new,priority,eta,priority_reason
0,ST2023-006,My internet connection has significantly slowe...,Connectivity failures,internet signal,"{\n ""priority"": ""Normal"",\n ""e...","{'priority': 'Normal', 'eta': '2 to 3 business...",Normal,2 to 3 business days,The user reports a significant slowdown in int...
1,ST2023-007,Urgent help required! My laptop refuses to sta...,Hardware problem,laptop,"{\n ""priority"": ""High urgency"",\n ...","{'priority': 'High urgency', 'eta': '1 busines...",High urgency,1 business day,The user has provided concrete evidence of a s...
2,ST2023-008,I've accidentally deleted essential work docum...,Data recovery,document loss,"{\n ""priority"": ""High urgency"",\n ...","{'priority': 'High urgency', 'eta': '1 busines...",High urgency,1 business day,The user has reported substantial data loss wh...
3,ST2023-009,Despite being in close proximity to my Wi-Fi r...,Connectivity failures,internet signal,"{\n ""priority"": ""Normal"",\n ""e...","{'priority': 'Normal', 'eta': '2 to 3 business...",Normal,2 to 3 business days,The issue is inconvenient but there is no evid...
4,ST2023-010,"My smartphone battery is draining rapidly, eve...",Hardware problem,battery,"{\n ""priority"": ""Normal"",\n ""e...","{'priority': 'Normal', 'eta': '2 to 3 business...",Normal,2 to 3 business days,The user reports a battery issue but there is ...

In [83]:
final_data_3 = data_with_parsed_model_output_3[["support_tick_id","support_ticket_text","category", "tag", "priority", "eta"]]

In [84]:
final_data_3

,support_tick_id,support_ticket_text,category,tag,priority,eta
0,ST2023-006,My internet connection has significantly slowe...,Connectivity failures,internet signal,Normal,2 to 3 business days
1,ST2023-007,Urgent help required! My laptop refuses to sta...,Hardware problem,laptop,High urgency,1 business day
2,ST2023-008,I've accidentally deleted essential work docum...,Data recovery,document loss,High urgency,1 business day
3,ST2023-009,Despite being in close proximity to my Wi-Fi r...,Connectivity failures,internet signal,Normal,2 to 3 business days
4,ST2023-010,"My smartphone battery is draining rapidly, eve...",Hardware problem,battery,Normal,2 to 3 business days
5,ST2023-011,I'm locked out of my online banking account an...,Connectivity failures,internet signal,High urgency,1 business day
6,ST2023-012,"My computer's performance is sluggish, severel...",Software problem,performance issue,Normal,2 to 3 business days
7,ST2023-013,I'm experiencing a recurring blue screen error...,Hardware problem,laptop,Normal,2 to 3 business days
8,ST2023-014,My external hard drive isn't being recognized ...,Data recovery,external hard drive,Normal,2 to 3 business days
9,ST2023-015,The graphics card in my gaming laptop seems to...,Hardware problem,"laptop, graphics card",Normal,2 to 3 business days
10,ST2023-016,I accidentally formatted my USB drive with cri...,Data recovery,"document loss, USB",Normal,2 to 3 business days
11,ST2023-017,"My computer's screen has gone black, and I can...",Hardware problem,laptop,Normal,2 to 3 business days
12,ST2023-018,"I accidentally spilled water on my laptop, and...",Data recovery,laptop,High urgency,1 business day
13,ST2023-019,"My USB flash drive is physically damaged, and ...",Data recovery,USB,High urgency,1 business day
14,ST2023-020,"The touchpad on my laptop has stopped working,...",Hardware problem,laptop,Normal,2 to 3 business days
15,ST2023-021,"My internet connection is frequently dropping,...",Connectivity failures,internet signal,Normal,2 to 3 business days
16,ST2023-022,Wi-Fi is inconsistent despite proximity to the...,Connectivity failures,internet signal,Normal,2 to 3 business days
17,ST2023-023,I accidentally formatted my USB drive with cru...,Data recovery,"document loss, USB",Normal,2 to 3 business days
18,ST2023-024,"My external hard drive isn't being recognized,...",Data recovery,hard_drive,Normal,2 to 3 business days
19,ST2023-025,I am experiencing a critical problem with my i...,NaN,NaN,High urgency,1 business day
20,ST2023-026,I hope this message finds you well. I am writi...,Software problem,document loss,Normal,2 to 3 business days

## **Creating a Draft Response**

In [85]:
# creating a copy of the data
data_4 = final_data_3.copy()

In [86]:
def response_4(prompt,ticket,category,tags,priority,eta):
    model_output = llm(
      f"""
      Q: {prompt}
      Support ticket: {ticket}
      category : {category}
      tag : {tags}
      priority: {priority}
      eta: {eta}
      A:
      """,
      max_tokens=512, #Number of tokens
      stop=["Q:"],
      temperature=0.001, #Temperature.
      echo=False,
    )

    temp_output = model_output["choices"][0]["text"]


    return temp_output

In [87]:
prompt_4 = """
    You are an IT service-desk response assistant.

    The support ticket has already been analyzed in Task 3. The supplied category,
    tag, priority, and ETA are authoritative inputs. Do not classify, change, or
    contradict them. Your only task is to draft the customer response.

    Response requirements:
    1. Write a concise, professional response of three to five sentences.
    2. Begin by acknowledging the problem and apologizing for the inconvenience.
    3. Refer to the assigned ETA exactly as supplied:
       - High urgency: within 1 business day.
       - Normal: within 2 to 3 business days.
    4. Do not promise an immediate resolution or a faster response than the
       supplied ETA.
    5. For Connectivity failures, say that the support team will investigate the
       connection issue and request relevant device, router, or error details.
    6. For Hardware problems, explain that a technician may request diagnostic
       details to determine the appropriate solution.
    7. For Software problems, request the application, operating-system, error-message,
       and recent-change details that are relevant to troubleshooting.
    8. For Data recovery, advise the customer to stop using the affected storage
       device when continued use could overwrite or worsen lost data, and request
       relevant recovery details.
    9. Never request passwords, authentication codes, full payment details, or other
       sensitive credentials.
    10. Do not invent actions already taken, diagnoses, guarantees, or completion times.

    Return only the plain-text customer response. Do not return JSON, a label, an
    explanation of the classification, or surrounding quotation marks.
"""

**Note** : For this task, we will not be using the *`extract_json_data`* function. Hence, the output from the model should be a plain string and not a JSON object.

In [88]:
#Applying generate_llama_response function on support_ticket_text column using explicit column names
start = time.time()
data_4['model_response_4'] = data_4.apply(
    lambda row: response_4(
        prompt_4,
        row['support_ticket_text'],
        row['category'],
        row['tag'],
        row['priority'],
        row['eta']
    ),
    axis=1
)
end = time.time()

Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      57.88 ms /    82 runs   (    0.71 ms per token,  1416.77 tokens per second)
llama_print_timings: prompt eval time =  297396.41 ms /   477 tokens (  623.47 ms per token,     1.60 tokens per second)
llama_print_timings:        eval time =   72427.20 ms /    81 runs   (  894.16 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =  370353.14 ms /   558 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      83.28 ms /   125 runs   (    0.67 ms per token,  1500.94 tokens per second)
llama_print_timings: prompt eval time =   48415.00 ms /    79 tokens (  612.85 ms per token,     1.63 tokens per second)
llama_print_timings:        eval time =  124488.48 ms /   124 runs   ( 1003.94 ms per token,     1.00 tokens per second)
llama_print_timings:       total time =  173757.31 ms /   203 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      88.86 ms /   138 runs   (    0.64 ms per token,  1552.92 tokens per second)
llama_print_timings: prompt eval time =   45838.30 ms /    75 tokens (  611.18 ms per token,     1.64 tokens per second)
llama_print_timings:        eval time =  122791.20 ms /   137 runs   (  896.29 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =  169513.33 ms /   212 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      58.29 ms /    87 runs   (    0.67 ms per token,  1492.56 tokens per second)
llama_print_timings: prompt eval time =   55053.27 ms /    88 tokens (  625.61 ms per token,     1.60 tokens per second)
llama_print_timings:        eval time =   76276.81 ms /    86 runs   (  886.94 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =  131900.49 ms /   174 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      59.33 ms /    92 runs   (    0.64 ms per token,  1550.54 tokens per second)
llama_print_timings: prompt eval time =   36870.03 ms /    61 tokens (  604.43 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =   80471.58 ms /    91 runs   (  884.30 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =  117934.14 ms /   152 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      61.48 ms /    94 runs   (    0.65 ms per token,  1528.93 tokens per second)
llama_print_timings: prompt eval time =   35398.63 ms /    59 tokens (  599.98 ms per token,     1.67 tokens per second)
llama_print_timings:        eval time =   83471.93 ms /    93 runs   (  897.55 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =  119489.68 ms /   152 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =     131.07 ms /   199 runs   (    0.66 ms per token,  1518.21 tokens per second)
llama_print_timings: prompt eval time =   47639.21 ms /    62 tokens (  768.37 ms per token,     1.30 tokens per second)
llama_print_timings:        eval time =  187575.60 ms /   198 runs   (  947.35 ms per token,     1.06 tokens per second)
llama_print_timings:       total time =  236611.94 ms /   260 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      93.09 ms /   142 runs   (    0.66 ms per token,  1525.45 tokens per second)
llama_print_timings: prompt eval time =   40534.13 ms /    64 tokens (  633.35 ms per token,     1.58 tokens per second)
llama_print_timings:        eval time =  128543.67 ms /   141 runs   (  911.66 ms per token,     1.10 tokens per second)
llama_print_timings:       total time =  170023.94 ms /   205 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =     160.82 ms /   236 runs   (    0.68 ms per token,  1467.52 tokens per second)
llama_print_timings: prompt eval time =   37541.34 ms /    60 tokens (  625.69 ms per token,     1.60 tokens per second)
llama_print_timings:        eval time =  250314.40 ms /   235 runs   ( 1065.17 ms per token,     0.94 tokens per second)
llama_print_timings:       total time =  289596.55 ms /   295 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      63.15 ms /    98 runs   (    0.64 ms per token,  1551.76 tokens per second)
llama_print_timings: prompt eval time =   42218.35 ms /    69 tokens (  611.86 ms per token,     1.63 tokens per second)
llama_print_timings:        eval time =   86147.87 ms /    97 runs   (  888.12 ms per token,     1.13 tokens per second)
llama_print_timings:       total time =  129005.35 ms /   166 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      87.54 ms /   130 runs   (    0.67 ms per token,  1485.02 tokens per second)
llama_print_timings: prompt eval time =   38040.44 ms /    63 tokens (  603.82 ms per token,     1.66 tokens per second)
llama_print_timings:        eval time =  120044.84 ms /   129 runs   (  930.58 ms per token,     1.07 tokens per second)
llama_print_timings:       total time =  158987.61 ms /   192 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      67.19 ms /   101 runs   (    0.67 ms per token,  1503.29 tokens per second)
llama_print_timings: prompt eval time =   39458.53 ms /    65 tokens (  607.05 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =   90019.92 ms /   100 runs   (  900.20 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =  130149.35 ms /   165 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =     115.05 ms /   171 runs   (    0.67 ms per token,  1486.26 tokens per second)
llama_print_timings: prompt eval time =   37488.78 ms /    62 tokens (  604.66 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =  163016.67 ms /   170 runs   (  958.92 ms per token,     1.04 tokens per second)
llama_print_timings:       total time =  201668.66 ms /   232 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =     150.16 ms /   227 runs   (    0.66 ms per token,  1511.77 tokens per second)
llama_print_timings: prompt eval time =   32747.07 ms /    53 tokens (  617.87 ms per token,     1.62 tokens per second)
llama_print_timings:        eval time =  204920.95 ms /   226 runs   (  906.73 ms per token,     1.10 tokens per second)
llama_print_timings:       total time =  239223.14 ms /   279 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      90.05 ms /   138 runs   (    0.65 ms per token,  1532.55 tokens per second)
llama_print_timings: prompt eval time =   37567.99 ms /    62 tokens (  605.94 ms per token,     1.65 tokens per second)
llama_print_timings:        eval time =  122003.60 ms /   137 runs   (  890.54 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =  160492.37 ms /   199 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      53.62 ms /    82 runs   (    0.65 ms per token,  1529.31 tokens per second)
llama_print_timings: prompt eval time =   31653.06 ms /    52 tokens (  608.71 ms per token,     1.64 tokens per second)
llama_print_timings:        eval time =   72341.94 ms /    81 runs   (  893.11 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =  104540.88 ms /   133 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =      55.08 ms /    84 runs   (    0.66 ms per token,  1525.17 tokens per second)
llama_print_timings: prompt eval time =   41059.01 ms /    58 tokens (  707.91 ms per token,     1.41 tokens per second)
llama_print_timings:        eval time =   85270.07 ms /    83 runs   ( 1027.35 ms per token,     0.97 tokens per second)
llama_print_timings:       total time =  126890.97 ms /   141 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =     179.61 ms /   272 runs   (    0.66 ms per token,  1514.36 tokens per second)
llama_print_timings: prompt eval time =   32235.96 ms /    54 tokens (  596.96 ms per token,     1.68 tokens per second)
llama_print_timings:        eval time =  245093.19 ms /   271 runs   (  904.40 ms per token,     1.11 tokens per second)
llama_print_timings:       total time =  279232.60 ms /   325 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =     138.68 ms /   214 runs   (    0.65 ms per token,  1543.12 tokens per second)
llama_print_timings: prompt eval time =   33672.57 ms /    55 tokens (  612.23 ms per token,     1.63 tokens per second)
llama_print_timings:        eval time =  191001.55 ms /   213 runs   (  896.72 ms per token,     1.12 tokens per second)
llama_print_timings:       total time =  226131.80 ms /   268 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =     107.96 ms /   160 runs   (    0.67 ms per token,  1481.98 tokens per second)
llama_print_timings: prompt eval time =  132935.11 ms /   201 tokens (  661.37 ms per token,     1.51 tokens per second)
llama_print_timings:        eval time =  144814.41 ms /   159 runs   (  910.78 ms per token,     1.10 tokens per second)
llama_print_timings:       total time =  278861.81 ms /   360 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =  102411.78 ms
llama_print_timings:      sample time =     117.70 ms /   180 runs   (    0.65 ms per token,  1529.35 tokens per second)
llama_print_timings: prompt eval time =  195396.30 ms /   318 tokens (  614.45 ms per token,     1.63 tokens per second)
llama_print_timings:        eval time =  177563.38 ms /   179 runs   (  991.97 ms per token,     1.01 tokens per second)
llama_print_timings:       total time =  374216.15 ms /   497 tokens

In [89]:
print("Time taken",(end-start))

Time taken 4188.941020965576

In [90]:
# Write the code to check the first five rows of the data to confirm whether the new column has been added
data_4['model_response_4'].head()

0     Dear Valued Customer,\n       We apologize fo...
1     Dear Valued Customer,\n       We sincerely ap...
2    Dear Valued Customer,\n      \n      We sincer...
3     Dear Valued Customer,\n       We apologize fo...
4     Dear Valued Customer,\n       We apologize fo...
Name: model_response_4, dtype: object

In [91]:
i = 4
print(data_4.loc[i, 'support_ticket_text'])

My smartphone battery is draining rapidly, even with minimal use. Can you help me identify and rectify this battery issue?

In [92]:
print(data_4.loc[i, 'model_response_4'])

 Dear Valued Customer,
       We apologize for the inconvenience you're experiencing with your smartphone battery draining rapidly despite minimal use. Our team will investigate this issue further and may request diagnostic details to determine the appropriate solution within the assigned ETA of 2 to 3 business days. Please do not attempt to replace the battery yourself as it may cause further damage to your device. Thank you for bringing this matter to our attention.

In [93]:
final_data_4 = pd.concat([final_data_3,data_4["model_response_4"]],axis=1)

In [94]:
final_data_4.rename(columns={"model_response_4":"response"},inplace=True)

In [95]:
final_data_4

,support_tick_id,support_ticket_text,category,tag,priority,eta,response
0,ST2023-006,My internet connection has significantly slowe...,Connectivity failures,internet signal,Normal,2 to 3 business days,"Dear Valued Customer,\n We apologize fo..."
1,ST2023-007,Urgent help required! My laptop refuses to sta...,Hardware problem,laptop,High urgency,1 business day,"Dear Valued Customer,\n We sincerely ap..."
2,ST2023-008,I've accidentally deleted essential work docum...,Data recovery,document loss,High urgency,1 business day,"Dear Valued Customer,\n \n We sincer..."
3,ST2023-009,Despite being in close proximity to my Wi-Fi r...,Connectivity failures,internet signal,Normal,2 to 3 business days,"Dear Valued Customer,\n We apologize fo..."
4,ST2023-010,"My smartphone battery is draining rapidly, eve...",Hardware problem,battery,Normal,2 to 3 business days,"Dear Valued Customer,\n We apologize fo..."
5,ST2023-011,I'm locked out of my online banking account an...,Connectivity failures,internet signal,High urgency,1 business day,"Dear Valued Customer,\n We apologize fo..."
6,ST2023-012,"My computer's performance is sluggish, severel...",Software problem,performance issue,Normal,2 to 3 business days,"Dear Valued Customer,\n \n We apolog..."
7,ST2023-013,I'm experiencing a recurring blue screen error...,Hardware problem,laptop,Normal,2 to 3 business days,"Dear Valued Customer,\n \n We apolog..."
8,ST2023-014,My external hard drive isn't being recognized ...,Data recovery,external hard drive,Normal,2 to 3 business days,"Dear Valued Customer,\n \n We apolog..."
9,ST2023-015,The graphics card in my gaming laptop seems to...,Hardware problem,"laptop, graphics card",Normal,2 to 3 business days,"Dear Valued Customer,\n We apologize fo..."
10,ST2023-016,I accidentally formatted my USB drive with cri...,Data recovery,"document loss, USB",Normal,2 to 3 business days,"Dear Valued Customer,\n We apologize fo..."
11,ST2023-017,"My computer's screen has gone black, and I can...",Hardware problem,laptop,Normal,2 to 3 business days,"Dear Valued Customer,\n We apologize fo..."
12,ST2023-018,"I accidentally spilled water on my laptop, and...",Data recovery,laptop,High urgency,1 business day,"Dear Valued Customer,\n \n We apolog..."
13,ST2023-019,"My USB flash drive is physically damaged, and ...",Data recovery,USB,High urgency,1 business day,"Dear Valued Customer,\n \n We apolog..."
14,ST2023-020,"The touchpad on my laptop has stopped working,...",Hardware problem,laptop,Normal,2 to 3 business days,"Dear Valued Customer,\n \n We apolog..."
15,ST2023-021,"My internet connection is frequently dropping,...",Connectivity failures,internet signal,Normal,2 to 3 business days,"Dear Valued Customer,\n We apologize fo..."
16,ST2023-022,Wi-Fi is inconsistent despite proximity to the...,Connectivity failures,internet signal,Normal,2 to 3 business days,"Dear Valued Customer,\n We apologize fo..."
17,ST2023-023,I accidentally formatted my USB drive with cru...,Data recovery,"document loss, USB",Normal,2 to 3 business days,"Dear Valued Customer,\n \n We apolog..."
18,ST2023-024,"My external hard drive isn't being recognized,...",Data recovery,hard_drive,Normal,2 to 3 business days,"Dear Valued Customer,\n \n We apolog..."
19,ST2023-025,I am experiencing a critical problem with my i...,NaN,NaN,High urgency,1 business day,"Dear Valued Customer,\n \n We sincer..."
20,ST2023-026,I hope this message finds you well. I am writi...,Software problem,document loss,Normal,2 to 3 business days,"Dear Valued Customer,\n We apologize fo..."

## **Model Output Analysis**

In [96]:
# Creating a copy of the dataframe of task-4
final_data = final_data_4.copy()

In [97]:
final_data['response'].value_counts()    # column name for the column containing ticket categories

response
 Dear Valued Customer,\n       We apologize for the inconvenience you've experienced with your internet connection. Our team will investigate the connection issue as soon as possible within the given ETA of 2 to 3 business days. In the meantime, please provide any relevant device, router, or error details that may help expedite the resolution process. Thank you for your patience and understanding.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
 Dear Valued Customer,\n       We sincerely apologize for the inconvenience you're experiencing with your laptop not starting. Our team understands the urgency of your situation and will prioritize your request accordingly. As per the provided ETA, we aim to resolve this issue within 1 business day. A technician may reach out to you for additional diagnostic details to determine the appropriate solution. In the meantime, please ensure that you do not attempt to use the laptop to prevent any potential data loss. Thank you for bringing this matter to our attention, and we will keep you updated on the progress.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
Dear Valued Customer,\n      \n      We sincerely apologize for the data loss incident you have experienced. We understand the importance of your work documents and the urgency of this situation. Our team will prioritize the data recovery process as per the assigned ETA of 1 business day.\n      \n      To ensure the best possible outcome, we kindly request that you avoid using the affected storage device to prevent any further data loss. Once the recovery process is initiated, we will keep you updated on the progress.\n      \n      Thank you for bringing this matter to our attention, and we appreciate your patience as we work to resolve this issue for you.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
 Dear Valued Customer,\n       We apologize for the inconvenience you're experiencing with your Wi-Fi signal. Our team will investigate the connection issue as soon as possible within the given ETA of 2 to 3 business days. In the meantime, please provide any relevant device, router, or error details that may help us diagnose the problem more effectively. Thank you for bringing this to our attention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
 Dear Valued Customer,\n       We apologize for the inconvenience you're experiencing with your smartphone battery draining rapidly despite minimal use. Our team will investigate this issue further and may request diagnostic details to determine the appropriate solution within the assigned ETA of 2 to 3 business days. Please do not attempt to replace the battery yourself as it may cause further damage to your device. Thank you for bringing this matter to our attention.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
 Dear Valued Customer,\n       We apologize for the inconvenience you're experiencing with accessing your online banking account. Our team is committed to resolving this issue as soon as possible, with a target resolution time of within 1 business day as per the assigned ETA. While we investigate the connection issue, please provide any relevant device, router, or error details that may help expedite the process. Thank you for your patience and understanding.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
Dear Valued Customer,\n      \n      We apologize for the inconvenience you're experiencing with your computer's performance. Our team will investigate this issue as soon as possible, within the assigned ETA of 2 to 3 business days. We kindly ask for your patience as we work to optimize your system for improved productivity.\n      \n      In the meantime, please provide the following details to help us troubleshoot the issue effectively:\n      1. Which specific application(s) are you experiencing the performance issue with?\n      2. What is the operating system version on your computer?\n      3. Can you please describe the error messages, if any, that you've encountered?\n      4. Have there been any recent changes to your system, such as software installations or updates?\n      \n      Thank you for bringing this matter to our attention, and we appreciate your cooperation as we work to resolve the issue.                                                                                                                                                                                                                                                                                                                                              1
Dear Valued Customer,\n      \n      We apologize for the inconvenience you're experiencing with your laptop's recurring blue screen errors causing frequent crashes. Our team will investigate this hardware issue as soon as possible, within the assigned ETA of 2 to 3 business days. We may request diagnostic details to determine the appropriate solution. In the meantime, please ensure the laptop is powered off when not in use to prevent any potential data loss. If you have any specific error messages related to this issue, please provide them to us for further analysis. Thank you for bringing this to our attention, and we appreciate your patience as we work to resolve this issue for you.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Dear Valued Customer,\n      \n      We apologize for the inconvenience you're experiencing with your external hard drive not being recognized by your computer. Our team will investigate the issue as soon as possible within the assigned ETA of 2 to 3 business days.\n      \n      To help us expedite the recovery process, please stop using the affected storage device to prevent any potential data loss or overwriting. Once you've secured the device, kindly provide us with the following details:\n         1. External hard drive make and model\n         2. Operating system version on your computer\n         3. Error messages, if any, that appear when attempting to connect the device\n         4. Recent changes to your computer or the external hard drive that may have caused the issue\n         5. Any relevant recovery details, such as the type of data lost and the estimated size of the data to be recovered.\n      \n      Thank you for choosing our services, and we appreciate your patience as we work to resolve your issue. If you have any further questions or concerns, please don't hesitate to contact us.                                                                                                                                           1
 Dear Valued Customer,\n       We apologize for the inconvenience you're experiencing with your laptop's graphics card. Our team will investigate the issue and may request diagnostic details to determine the appropriate solution within the assigned ETA of 2 to 3 business days.\n       Please do not attempt to force the laptop to perform beyond its current capabilities as this could potentially worsen the issue. We appreciate your patience as we work to resolve this matter for you.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
 Dear Valued Customer,\n       We apologize for the inconvenience you have experienced with the formatting of your USB drive containing critical work files. Our team will begin the data recovery process as soon as possible within the assigned ETA of 2 to 3 business days. In the meantime, we strongly advise you to stop using the affected storage device to prevent any further data loss or overwriting of existing files. If you have any relevant recovery details to provide, please share them with our team to expedite the process. Thank you for bringing this matter to our attention. We appreciate your patience as we work to recover your data.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
 Dear Valued Customer,\n       We apologize for the inconvenience you're experiencing with your laptop's screen. Our team will investigate the issue as soon as possible within the assigned ETA of 2 to 3 business days. If you have any relevant diagnostic details to provide, such as error messages or recent changes to your system, please share them with us to help expedite the resolution process. Thank you for your patience as we work to get your laptop functioning properly again.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
Dear Valued Customer,\n      \n      We apologize for the inconvenience you've experienced with your laptop. We understand the importance of your data and will make every effort to help you recover it as soon as possible. In accordance with the high urgency priority you've assigned to this issue, our team will begin investigating the data recovery process within one business day. We appreciate your patience as we work diligently to determine the best course of action for your situation. In the meantime, please avoid using the affected storage device to prevent further data loss. If you have any relevant recovery details to share with us, such as the type of data lost or the cause of the water damage, please provide them to help expedite the process. We will keep you updated on our progress. Thank you for choosing our services.                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Dear Valued Customer,\n      \n      We apologize for the inconvenience you're experiencing with your physically damaged USB flash drive. Our team understands the importance of your critical files and will prioritize your request. We aim to complete the data recovery process within the assigned ETA of 1 business day.\n      \n      To ensure the best possible outcome, please stop using the affected storage device to prevent further data loss or corruption. Once you've secured the device, please provide us with the following details to help expedite the recovery process:\n          - Make and model of the USB flash drive\n          - Size of the storage device\n          - File types and sizes of the critical files to be recovered\n          - Any error messages or symptoms you've encountered\n          - Recent changes to the USB flash drive or your computer that may be related to the issue\n      \n      Thank you for choosing our services for your data recovery needs. We'll keep you updated on the progress throughout the process. If you have any questions or concerns, please don't hesitate to contact us.                                                                                                                                      1
Dear Valued Customer,\n      \n      We apologize for the inconvenience you're experiencing with your laptop's touchpad. Our team will investigate the issue as soon as possible, following the assigned priority of normal, with an estimated resolution time of 2 to 3 business days.\n      \n      To help us better understand the problem, could you please provide any relevant diagnostic details? This may include the make and model of your laptop, as well as any error messages that appear when you attempt to use the touchpad.\n      \n      Thank you for bringing this issue to our attention, and we appreciate your patience as we work to resolve it.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1

In [98]:
final_data["priority"].value_counts() #the column name for the column containing the priorities of the ticket.

priority
Normal          15
High urgency     6
Name: count, dtype: int64

In [99]:
final_data["eta"].value_counts()  #the column name for the column containing ticket resolution ETA.

eta
2 to 3 business days    15
1 business day           6
Name: count, dtype: int64

In [100]:
final_data.groupby(['category', 'eta']).support_tick_id.count() # Group by based on the categories and ETA.

category               eta
Connectivity failures  1 business day          1
                       2 to 3 business days    4
Data recovery          1 business day          3
                       2 to 3 business days    4
Hardware problem       1 business day          1
                       2 to 3 business days    5
Software problem       2 to 3 business days    2
Name: support_tick_id, dtype: int64